#### Tensorflow is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into hands of others)

#### WHY to use: Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as Tensorflow. Because it contains many of the most common machine learning functions.

In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


#### Premise: Turn data into numbers (tensors) and build machine learning algorithms to find patterns.

#### 4. Tensors and numpu

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.16.1'

## 1. Create tensors

In [7]:
# scalar - int
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
scalar.ndim

0

In [10]:
# vector - int
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [11]:
vector.ndim

1

In [13]:
# matrix - int
matrix = tf.constant([[10,4],[2,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 2,  5]])>

In [14]:
matrix.ndim

2

In [20]:
# float
mat2 = tf.constant([[2.3,4.0,],[4.2,6.5],[6.0,3.0]])
mat2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.3, 4. ],
       [4.2, 6.5],
       [6. , 3. ]], dtype=float32)>

In [21]:
mat2.ndim

2

In [22]:
# Tensors with more than 2 dimensions are very useful in real-life

In [24]:
mat = tf.constant([[[1,2,3],[3,4,5]],
                  [[7,8,9],[3,6,1]]])
mat

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[7, 8, 9],
        [3, 6, 1]]])>

In [26]:
mat.ndim

3

In [27]:
mat4 = tf.constant([[[[1,2,3],[4,5,6]],[[5,6,7],[2,3,6]]],
                   [[[5,3,1],[3,2,5]],[[2,1,4],[5,3,2]]]])
mat4

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]],

        [[5, 6, 7],
         [2, 3, 6]]],


       [[[5, 3, 1],
         [3, 2, 5]],

        [[2, 1, 4],
         [5, 3, 2]]]])>

In [28]:
mat4.ndim

4

In [29]:
# Here, 0,1,2,3,4 refers to the rank. Therefore 3 dimension means rank 3 tensor

In [37]:
matrix = tf.Variable([1,2,3])
matrix

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [38]:
matrix[2].assign(4)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([1, 2, 4])>

### Generate random tensors

In [78]:
# .seed(42) --> specific random values
# .from_non_deterministic_state() --> random values

random1 = tf.random.Generator.from_seed(34)
random = tf.random.Generator.from_non_deterministic_state()
random = random.normal(shape=(3,2,3))
random1 = random1.normal(shape=(3,2))

In [79]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.5181769 ,  1.4020647 ],
       [ 1.5570306 , -0.96762174],
       [ 0.495291  , -0.648484  ]], dtype=float32)>

In [80]:
random

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 1.2565569 , -0.6692918 ,  2.069152  ],
        [-1.0267544 , -0.5903662 ,  0.49037948]],

       [[ 0.7032688 ,  1.7037903 ,  1.4657477 ],
        [-0.39143378,  0.41819862,  0.51578647]],

       [[ 0.5173651 , -0.48453388, -0.3014805 ],
        [ 0.93337864, -1.1592852 , -1.0052398 ]]], dtype=float32)>

## Shuffle tensors

#### Let say you have 15,000 images of cats and dogs. In which, first 10,000 images are of cats and next 5,000 images are of dogs. This order could effect how a neural network learns (if may overfit by learning the order of the data).

#### Instead, I will be a good idea to move you data around

In [84]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [89]:
tf.random.shuffle(not_shuffled, seed=64)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [100]:
# Set the global random seed
tf.random.set_seed(64)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=64)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

### zeros and ones

Note: Useful when to define BAIS

In [6]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
tf.ones(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## 3. Manipulating tensors

In [11]:
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [12]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [14]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [15]:
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]])>

In [17]:
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]])>

# Matrix mutliplication

One of the most common operations in machine learning algorithms is [matrix multiplication]

TensorFlow implements this matrix multiplication functionality in the [`tf.matmul()`]

The main two rules for matrix multiplication to remember are:
1. The inner dimensions must match:
  * `(3, 5) @ (3, 5)` won't work
  * `(5, 3) @ (3, 5)` will work
  * `(3, 5) @ (5, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

> 🔑 **Note:** '`@`' in Python is the symbol for matrix multiplication.

In [18]:
# Matrix multiplication with tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [20]:
# Matrix multiplication with python

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [21]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [23]:
# Won't work, can't multiply
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 