## Reshape and transpose

*tf.transform(a)*

*tf.reshape(a, shape=(2,3))*

In [27]:
import tensorflow as tf
import numpy as np

In [2]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [8]:
# 1. Reshape

In [9]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [6]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [7]:
# 2. Transform

In [11]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]])>

In [13]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [15]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

### Values for reshape and transpose are not same

In [16]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [17]:
# Concept wise
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [18]:
# sequentially
tf.reshape(X, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## Changing the datatype of a tensor


*tf.cast(x, dtype=tf.float32)*

In [19]:
a = tf.constant(1.3245322)
a

<tf.Tensor: shape=(), dtype=float32, numpy=1.3245322>

In [20]:
tf.cast(a, dtype=tf.float16)

<tf.Tensor: shape=(), dtype=float16, numpy=1.324>

In [22]:
c = tf.constant([[1.3245322, 4.2453423],[7.436624,7.246854]])
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.3245322, 4.2453423],
       [7.436624 , 7.246854 ]], dtype=float32)>

In [23]:
tf.cast(c, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.324, 4.246],
       [7.438, 7.246]], dtype=float16)>

In [24]:
tf.cast(c, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [7, 7]])>

## Absolute value of tensor

*tf.abs(x)*

In [25]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [26]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

## Find min, max, mean, sum (Aggregation)


*tf.reduce_max()*

*reduce_min, reduce_mean*

*reduce_sum*


In [28]:
E = tf.constant(np.random.randint(0, 100, 50))

In [29]:
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 5, 91, 10, 79, 84, 98, 55,  2, 15, 90, 67, 51, 33, 36, 11, 67,  8,
       31, 36, 80,  8, 63, 49, 83, 46, 74, 21, 64, 87, 23, 11, 41, 20, 49,
       29, 72, 36,  4, 24, 90, 26, 69, 77, 96, 43, 63,  4, 62, 96, 17])>

In [30]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [31]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [32]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

In [33]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2396>

## position of min and max

*tf.argmax()*

*argmin()*

In [34]:
F = tf.constant(np.random.random(50))

In [35]:
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.37178765, 0.9799144 , 0.43733918, 0.60848649, 0.86778188,
       0.79112995, 0.63667573, 0.1694978 , 0.57545596, 0.07377197,
       0.94996584, 0.60396345, 0.77180633, 0.94551204, 0.68396634,
       0.27102271, 0.0298382 , 0.83058985, 0.09879122, 0.69724196,
       0.47921103, 0.43708613, 0.86960939, 0.8998794 , 0.67936138,
       0.40493308, 0.98416155, 0.62802764, 0.1650664 , 0.32194169,
       0.9750878 , 0.57025068, 0.6712278 , 0.49967277, 0.54912937,
       0.80008506, 0.66172931, 0.68609321, 0.27551422, 0.19875523,
       0.28239469, 0.1436623 , 0.90283325, 0.50834112, 0.73715421,
       0.61016838, 0.55098724, 0.78284103, 0.87454593, 0.46711455])>

In [36]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=26>

In [37]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

## Squeezing a tensor

*removes single_dimensions from the tensors*

*tf.squeeze(X)*

In [43]:
G = tf.constant(np.random.randint(0,100, 50), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
array([[[[[61, 66, 68,  9, 89, 57, 63, 90, 22, 74, 74, 44, 28, 27,  2,
           48,  2, 65, 23,  9, 74,  5, 91, 77, 24, 15, 57, 53, 30, 78,
           12, 70,  5, 91, 89, 49, 91, 44,  2,  2, 80,  2, 94, 17, 65,
           66, 10, 39, 90, 61]]]]])>

In [44]:
G_squeeze = tf.squeeze(G)

In [45]:
G_squeeze

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([61, 66, 68,  9, 89, 57, 63, 90, 22, 74, 74, 44, 28, 27,  2, 48,  2,
       65, 23,  9, 74,  5, 91, 77, 24, 15, 57, 53, 30, 78, 12, 70,  5, 91,
       89, 49, 91, 44,  2,  2, 80,  2, 94, 17, 65, 66, 10, 39, 90, 61])>

In [46]:
G.ndim, G_squeeze.ndim

(5, 1)

# One-hot encoding

*tf.one_hot(x, depth=4)*

In [51]:
some_list = [5,3,7,9]

In [57]:
tf.one_hot(some_list, depth=np.max(some_list))

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [58]:
# Custom values with one-hot encoding

In [66]:
other_list = [0,1,2,3]
tf.one_hot(other_list, depth=np.max(other_list), on_value="We're live", off_value="We're offline")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b"We're live", b"We're offline", b"We're offline"],
       [b"We're offline", b"We're live", b"We're offline"],
       [b"We're offline", b"We're offline", b"We're live"],
       [b"We're offline", b"We're offline", b"We're offline"]],
      dtype=object)>

### Square, root, log

*tf.square()*

*tf.sqrt()*

*tf.math.log()*

In [69]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [70]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [71]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [74]:
# Change to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [75]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [76]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Manipulating tf.Variable tensors

*a.assign()*

*a.assign_add()*

In [80]:
G = tf.Variable(np.arange(1, 5))
G

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [81]:
G.assign([3,1,5,6])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 1, 5, 6])>

In [84]:
# assign + add
G.assign_add([4,2,1,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7,  3,  6, 13])>

## Tensors and numpy

*tf.constant(np.arange(1,4))*

*np.array(X)*

*X.numpy()*

In [87]:
# Create a tensor from numpy array

I = tf.constant(np.arange(1,5))
I

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [91]:
# Convert tensor to numpy
# WHY: Because there can be situations where tensors do not have sufficient functions, therefore numpy's methods can be helpful

# Using np.array()
J = np.array(I)
J, type(J)

(array([1, 2, 3, 4]), numpy.ndarray)

In [94]:
# using .numpy()
I.numpy(), type(I.numpy())

(array([1, 2, 3, 4]), numpy.ndarray)